version: '3'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - miniostack
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
      MINIO_DEFAULT_BUCKETS: mybucket
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

networks:
  miniostack:
    driver: bridge

volumes:
  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./minio/data
